// Generated by CoffeeScript 1.6.3
(function() {
  var Kaleidoverse;

  window.Kaleidoverse = Kaleidoverse = (function() {
    function Kaleidoverse() {
      $.cookie.json = true;
    }

    Kaleidoverse.prototype.run = function() {
      var login;
      login = $.cookie('login');
      if (login) {
        return this.display_main(login);
      } else {
        return this.display_login();
      }
    };

    Kaleidoverse.prototype.display_main = function(login) {
      var data;
      data = {
        'login': login
      };
      return $('.primary-content').html(Jemplate.process('main.html', data));
    };

    Kaleidoverse.prototype.display_login = function() {
      return $('.primary-content').html(Jemplate.process('login.html'));
    };

    Kaleidoverse.prototype.do_login = function() {
      var login, token;
      token = $("input[name$='token']").val();
      if (token) {
        login = {
          auth_token: token
        };
        $.cookie('login', login, {
          path: '/'
        });
        return this.run();
      }
    };

    Kaleidoverse.prototype.do_logout = function() {
      $.removeCookie('login', {
        path: '/'
      });
      return this.run();
    };

    return Kaleidoverse;

  })();

  window.kaleidoverse = function() {
    window.ko = new Kaleidoverse;
    return ko.run();
  };

}).call(this);
