// Generated by CoffeeScript 1.6.3
(function() {
  var Kaleidoverse;

  window.Kaleidoverse = Kaleidoverse = (function() {
    function Kaleidoverse() {
      window.say = console.log;
      $.cookie.json = true;
      this.github_owner = 'veradox';
      this.github_repo = 'kaleidoverse';
      this.state = $.cookie('state');
    }

    Kaleidoverse.prototype.run = function() {
      if (this.state) {
        this.display('main', {
          'state': this.state
        });
        return this.github = new Github({
          token: this.state.token,
          auth: "oauth"
        });
      } else {
        return this.display('login');
      }
    };

    Kaleidoverse.prototype.display = function(view, data) {
      return $('.primary-content').html(Jemplate.process("" + view + ".html", data));
    };

    Kaleidoverse.prototype.lightbox = function(view) {
      return $.colorbox({
        html: Jemplate.process("" + view + ".html"),
        height: '50%',
        width: '50%'
      });
    };

    Kaleidoverse.prototype.do_token_login = function() {
      var state;
      state = {
        token: '1234567890',
        login: 'ingydotnet'
      };
      return $.cookie('state', state, {
        path: '/'
      });
    };

    Kaleidoverse.prototype.do_logout = function() {
      $.removeCookie('state', {
        path: '/'
      });
      return this.run();
    };

    Kaleidoverse.prototype.do_fork = function() {
      this.repo = this.github.getRepo(this.github_owner(this.github_repo));
      return this.repo.fork(function(err) {
        if (err) {
          return console.log(err);
        } else {
          return alert("You Forked Me!");
        }
      });
    };

    return Kaleidoverse;

  })();

  window.kaleidoverse = function() {
    window.ko = new Kaleidoverse;
    return ko.run();
  };

}).call(this);
